server:
  port: 8083

spring:
  application:
    name: bank-currency-micro

  cache:
    type: redis
  data:
    redis:
      # 🚀 SADECE DEĞİŞKEN ADLARI:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

eureka:
  client:
    service-url:
      # 🚀 SADECE DEĞİŞKEN ADI:
      defaultZone: ${EUREKA_URL}
  instance:
    prefer-ip-address: true

# ==========================================
# 🔭 YENİ EKLENDİ: ACTUATOR (İSTİHBARAT) AYARLARI
# ==========================================
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true