server:
  port: 8082

spring:
  application:
    name: notification-service

  rabbitmq:
    # 🚀 SADECE DEĞİŞKEN ADLARI:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

eureka:
  client:
    service-url:
      # 🚀 SADECE DEĞİŞKEN ADI:
      defaultZone: ${EUREKA_URL}