server:
  port: 8082

spring:
  application:
    name: notification-service

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password

eureka:
  client:
    service-url:
      # 🚀 TİRELİ VE GÜVENLİ SERVİS ADI: discovery-server
      defaultZone: http://discovery-server:8761/eureka/