server:
  port: 8081

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        # 🚀 1. ROKET: Tarayıcının öncü (OPTIONS) CORS isteklerini havada yakala!
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            # 🚀 2. ROKET: Origins ve Methods kısımlarını tireli liste (-) yapıyoruz, Spring böyle daha iyi anlar.
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"

      routes:
        - id: monolith-route
          # 🚀 AZ ÖNCEKİ HAYATİ DÜZELTME: Eureka'yı bekleme, doğrudan tanka git!
          uri: http://bank_backend_micro:8080
          predicates:
            - Path=/api/v1/**
          #filters:
          #  - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/