server:
  port: 8081

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

spring:
  application:
    name: api-gateway
  cloud: # 🚀 DİKKAT: application ile AYNİ hizada olmalı!
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

      routes:
        - id: monolith-route
          # 🚀 EUREKA'NIN GÜCÜ: Doğrudan IP yazmak yok, ismini söylüyoruz o buluyor!
          uri: lb://BANK-DEMO-BACKEND
          predicates:
            - Path=/api/v1/**
          filters:
            - AuthenticationFilter # 👮 Bordo Bereli Sınır Polisini kapıya diktik!

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/