server:
  port: 8080

spring:
  application:
    name: bank-demo-backend

  datasource:
    # 🚀 SADECE DEĞİŞKEN ADLARI:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    # 🚀 SADECE DEĞİŞKEN ADLARI:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

# 🚀 ESKİ AJANIN ŞİFRESİ (Backend'in çökmemesi için şart)
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 1 gün

eureka:
  client:
    service-url:
      # 🚀 SADECE DEĞİŞKEN ADI:
      defaultZone: ${EUREKA_URL}
  instance:
    prefer-ip-address: true