# 1. DİNLEME NOKTASI (Nereden İstihbarat Gelecek?)
input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

# 2. SÜZGEÇ (Gerekirse veriyi burada şekillendiririz - Şimdilik boş bırakıyoruz)
filter {
  # İleride "Sadece ERROR'ları al" veya "Tarih formatını düzelt" gibi komutları buraya yazacağız.
}

# 3. TESLİMAT NOKTASI (İstihbarat Nereye Gidecek?)
output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "bank-logs-%{+YYYY.MM.dd}" # Logları gün gün arşiv klasörlerine ayırıyoruz
  }
  
  # (Opsiyonel) Biz de ekrandan görelim diye terminale de basıyoruz
  stdout {
    codec => rubydebug
  }
}